ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-59' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\birmo\OneDrive\Рабочий стол\Election_Bot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "C:\Users\birmo\OneDrive\Рабочий стол\Election_Bot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\birmo\OneDrive\Рабочий стол\Election_Bot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\birmo\OneDrive\Рабочий стол\Election_Bot\.venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\birmo\OneDrive\Рабочий стол\Election_Bot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\birmo\OneDrive\Рабочий стол\Election_Bot\.venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\birmo\OneDrive\Рабочий стол\Election_Bot\bot.py", line 441, in dailog
    message = await message.answer(text=data['candidates'][0], reply_markup=InlineKeyboardMarkup(row_width=3)
  File "C:\Users\birmo\OneDrive\Рабочий стол\Election_Bot\.venv\lib\site-packages\aiogram\types\input_file.py", line 40, in __init__
    self._file = open(path_or_bytesio, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'database/bot_photos\\TLD2-e9T0qw.jpg'
